site_name: Science Encyclopedia
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
nav:
  - Home: index.mkd
  - Physics: physics/index.mkd
  - Chemistry: chemistry/index.mkd
